### ISSUE TITLE
Support for Grafana v6.4?

### ISSUE THREAD

**Issue by kleisauke** [performancecopilot/grafana-pcp#16]
I noticed that this plugin doesn't work for Grafana v6.4.x. To reproduce:
```bash
git clone https://github.com/kleisauke/pcp-preview.git
cd pcp-preview
docker build -t pcp-preview .
docker run -d --privileged -p 3000:3000 pcp-preview
```

The following errros appear when you try to open a dashboard (for e.g. the PCP Redis Host Overview dashboard):
```
PCP Redis plugin failed
Error: ace is not defined Evaluating http://localhost:3000/public/plugins/performancecopilot-pcp-app/datasources/redis/module.js Loading plugins/performancecopilot-pcp-app/datasources/redis/module
```
![grafana-pcp](https://user-images.githubusercontent.com/12746591/66499484-3a0c0f00-eac0-11e9-9872-3e8da1323b7f.png)

Note that it's working fine when I install Grafana v6.3.6:
```diff
diff --git a/Dockerfile b/Dockerfile
index 1111111..2222222 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -56,7 +56,7 @@ RUN rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial \
 
 # Install PCP, Redis and Grafana
 RUN dnf -y install --setopt=tsflags=nodocs \
-        redis grafana \
+        redis grafana-6.3.6 \
         $(ls /pcp-rpms/pcp-{5,libs-5,conf,selinux}*.x86_64.rpm) \
     && dnf clean all \
     && systemctl enable redis pmcd pmlogger pmproxy grafana-server grafana-configuration
```

Let me know if you need further information.

**Comment by andreasgerstmayr** [comment]
Thanks for the report! Just looked at the source of Grafana 6.4, they've replace the Ace editor with Slate, so the grafana-pcp syntax highlighting and autocompletion needs to be adapted to the new Slate API. I'll work on it in 1-2 weeks.

**Comment by tlerea1** [comment]
This is happening to me as well!

**Comment by christianhorn** [comment]
+1, I guess everybody doing this setup today will install latest grafana and hit this issue

**Comment by 307105141** [comment]
Grafana version 6.4, there is no latest plug-in yet.？
Where can download Grafana v6.3.6？ there are experts know, for a link.

**Comment by natoscott** [comment]
@307105141 earlier versions of Grafana can be downloaded from:

https://grafana.com/grafana/download

click on the 'Other versions' drop-down menu in the top right corner, and the rest of the page changes to show instructions for installing the selected version.

**Comment by 307105141** [comment]
tks。

**Comment by 307105141** [comment]
Why the plug-in cannot be loaded after version Grafana 6.3 is installed .

**Comment by 307105141** [comment]
Install version 6.3, but configure the data source to report an error: 
HTTP Error 502: Bad Gateway, please check the datasource and pmproxy settings. To use this data source, please configure the URL in the query editor.

Do you have a successful case to share. 
According to the Red Book installation deployment, but it has not been able to.

**Comment by oleksandrborniak** [comment]
@andreasgerstmayr Do you have any ETA for this issue?

**Comment by natoscott** [comment]
@oleksandrborniak Andreas is currently travelling, but I believe it'll be a high priority issue for him when back online.

**Comment by andreasgerstmayr** [comment]
I've just release grafana-pcp 2.0.0-beta1 which includes support for Grafana 6.5+, and drops support for Grafana < 6.5.

It didn't undergo much testing (therefore it's still a beta release), but so far everything looks good (tested with Grafana's 6.5.2 docker image).

**Comment by oleksandrborniak** [comment]
@andreasgerstmayr  Thank you! Great news.

**Comment by ranicete** [comment]
Hi, i'm seeing this issue on my system. please see error msg below.

Im using the following version:
grafana pcp v1.0.7
grafana Version 6.6.1
pmcd: Version 4.3.1-1
Redis version=5.0.3

ace is not defined Evaluating http://10.100.168.161:3000/public/plugins/performancecopilot-pcp-app/datasources/bpftrace/module.js Loading plugins/performancecopilot-pcp-app/datasources/bpftrace/module

i also updated grafana pcp to 2.0.0 and i see the same issue

**Comment by andreasgerstmayr** [comment]
@ranicete : Based on https://github.com/performancecopilot/pcp/issues/793, I think this issue is resolved?

**Comment by ranicete** [comment]
Yes and thank you very much for your support. 

Please excuse any typos.  Sent from my iPhone
