### ISSUE TITLE
Data source is unavailable on windows platform

### ISSUE THREAD

**Issue by maokelong** [performancecopilot/grafana-pcp#182]
**Data source:** NA

**Describe the bug**
Even if PCP has been installed and enabled, none of these data sources appears on windows platform: PCP Redis, PCP Vector, PCP bpftrace.

**To Reproduce**
1. Install the latest Grafana released for windows platform on [Grafana's offcial website](https://grafana.com/grafana/download?pg=get&platform=windows&plcmt=selfmanaged-box1-cta1) ;
2. Install the latest PCP plugin by unziping it's release into data/plugins
3. Enable PCP plugin
4. Try to add data sources for PCP plugin

**Expected behavior**
Able to add PCP data source.

**Screenshots**
![image](https://user-images.githubusercontent.com/12730912/204088959-e32a3cf5-bd34-46ea-a56c-9692573f399f.png)
![image](https://user-images.githubusercontent.com/12730912/204089176-2ada7dc7-8015-44c7-bd65-4722cccfe712.png)

**Versions (please complete the following information):**
 - Performance Co-Pilot:
 - Grafana:9.2.6
 - grafana-pcp:5.1.1
- Redis (if applicable):NA

**Additional context**

**Comment by kachini** [comment]
same issue on Linux with Grafana 9.4.1 grafana-pcp 5.1.1 ,  wondering if there any solution.

**Comment by kachini** [comment]
ah, probably there is a typo in docs with name plugin names: 
If I add following to grafana.ini,  I can see datasources:

allow_loading_unsigned_plugins = performancecopilot-pcp-app,pcp-vector-datasource,pcp-bpftrace-datasource,pcp-flamegraph-panel,pcp-troubleshooting-panel,pcp-breadcrumbs-panel,pcp-redis-datasource

**Comment by sfeifer** [comment]
Hi. I corrected that line in the docs and opened a pull request here, #193.
