### ISSUE TITLE
dist directory does not exist

### ISSUE THREAD

**Issue by christianhorn** [performancecopilot/grafana-pcp#19]
https://github.com/performancecopilot/grafana-pcp/blob/master/docs/pcp-redis.md says
~~~
clone the github source: git clone https://github.com/performancecopilot/grafana-pcp-redis
change directory to the just-cloned datasource: cd grafana-pcp-redis
symlink the dist directory into the grafana plugins directory: sudo ln -sf $PWD/dist /var/lib/grafana/plugins/pcp
~~~
..but it seems like there is currently no dist directory with a build.

**Comment by goodwinos** [comment]
Hi Christian, the dist directory is in the release-1.0.0 branch.
git checkout release-1.0.0

Cheers

**Comment by christianhorn** [comment]
Hi, I see.
I think modifying https://github.com/performancecopilot/grafana-pcp/blob/master/docs/pcp-redis.md will help people to directly follow the instructions there. The current steps do not work with head.
cheers,
Chris

**Comment by goodwinos** [comment]
current release is now release-1.0.1
