### ISSUE TITLE
Update the Grafana version in grafana-pcp

### ISSUE THREAD

**Issue by jainnikhil30** [performancecopilot/grafana-pcp#192]
**Data source:** (please fill in)

**Describe the bug**
The current Grafana version that gets installed with the latest grafana-pcp is 9.0.9, which more than a year old now. The latest version of Grafana is 10.2. Its been almost a year after last release of grafana-pcp. Please update the Grafana version.

**Versions (please complete the following information):**
 - grafana-pcp: 5.1.1.

**Additional context**
There are some really good features in the latest Grafana v10 which we are not able to use.

**Comment by kdelee** [comment]
In 9.4 onwards there have alert exporting and provisioning which my team is particularly interested in

**Comment by natoscott** [comment]
| The current Grafana version that gets installed with the latest grafana-pcp is 9.0.9

Can you explain what you mean a bit more @jainnikhil30 - I'm not understanding how grafana-pcp installs any specific version of Grafana?  AIUI from chatting to @sfeifer the current version of grafana-pcp works fine with Grafana 10.  Thanks.

**Comment by jainnikhil30** [comment]
@natoscott Thanks for the update and apologies for the confusion. When we were trying to install grafana-pcp, it installs grafana as a dependency and the version that it installed was 9.0.9, is that because the latest version in RHEL base repos is 9.0.9 ? If it works well with Grafana 10 then I think we are good.

**Comment by natoscott** [comment]
Ah I see, yes, I believe its an independent issue then - RHEL-9.x will update to Grafana 10 in due course, earlier versions of RHEL are on a stricter update cycle now and likely will be fixes only (i.e. not major version rebases).
