### ISSUE TITLE
Bad gateway

### ISSUE THREAD

**Issue by mnlipp** [performancecopilot/grafana-pcp#22]
Sorry, this is probably a silly question but your documentation is extremely short.

I have configured everything I could in grafana, but when adding the PCP datasource I get "Error: Bad Gateway. To use this data source, please configure the URL in the query editor."

I have no idea what I should configure instead of the default:
![image](https://user-images.githubusercontent.com/1446020/68040930-af3dbf00-fccf-11e9-8b28-4b990fde14ea.png)

From what I have understood, this is where the data comes from. (Grafana server and pmproxy running on the same host). I've check with netstat that pmproxy is listening on this port.

**Comment by mnlipp** [comment]
Silly, indeed. What I have been seeing was the "greyed out" proposal for the value, not the actual value. It became clear when I switched to the light theme.

**Comment by 307105141** [comment]
I also encounter this situation. Can you give me some advice.

**Comment by mnlipp** [comment]
I simply entered the value for the URL. When using the dark theme, it *looks* as if it was entered already. But this is just the default proposal used as background "image" for the field.

**Comment by andreasgerstmayr** [comment]
@307105141: can you double-check if the URL field contains a value (i.e. move the cursor inside), and check if pmproxy is running and listening on the specified port? (e.g. `sudo ss -lntp` and check the Local Address:Port column)

@mnlipp: The data source configuration box comes directly from Grafana, do you mind opening a ticket there (to improve the UX of this box by using colors with more contrast)?

**Comment by mnlipp** [comment]
@andreasgerstmayr I wouldn't mind. But I think of it more as a personal problem. I've always felt that dark themes stress my eyes and have never understood why people like them. So I'd only consider this a bug if people who are accustomed to dark themes have a problem with the contrast in Grafana's particular version of a dark theme.
