### ISSUE TITLE
problem to install grafana-pcp plugin

### ISSUE THREAD

**Issue by jaehyuck-kwak** [performancecopilot/grafana-pcp#33]
Hi, 
I am newbie to grafana and grafana-pcp plugin.

I am in trouble to install grafana-pcp plugin. 

I installed grafana latest version using rpm.
$ rpm -qa | grep grafana
grafana-6.6.1-1.x86_64

I built grafana-pcp from the source. Here is the logs:
$ git clone https://github.com/performancecopilot/grafana-pcp.git
$ cd grafana-pcp
$ make
yarn install
yarn install v1.22.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@grafana/ui > @grafana/slate-react > slate-react-placeholder@0.2.8" has unmet peer dependency "slate-react@>=0.22.0".
[4/4] Building fresh packages...
Done in 6.14s.
yarn run build
yarn run v1.22.0
$ webpack --config webpack.config.prod.js
clean-webpack-plugin: /root/grafana-pcp-src/grafana-pcp/dist has been removed.
Hash: a02d25235442068f3faa
Version: webpack 4.41.5
Child
    Hash: a02d25235442068f3faa
    Time: 14138ms
    Built at: 2020-02-13 11:31:07
                                                    Asset       Size  Chunks             Chunk Names
                         ./datasources/bpftrace/module.js   77.7 KiB       0  [emitted]  ./datasources/bpftrace/module
                            ./datasources/redis/module.js     45 KiB       1  [emitted]  ./datasources/redis/module
                           ./datasources/vector/module.js   61.3 KiB       2  [emitted]  ./datasources/vector/module
                                              ./module.js   7.57 KiB       3  [emitted]  ./module
                            ./panels/flamegraph/module.js   91.2 KiB       4  [emitted]  ./panels/flamegraph/module
                                                  LICENSE   11.1 KiB          [emitted]
                                                   NOTICE  423 bytes          [emitted]
                                                README.md   2.16 KiB          [emitted]
                            components/config/config.html  630 bytes          [emitted]
                         components/config/css/config.css  202 bytes          [emitted]
                dashboards/pcp-bpftrace-flame-graphs.json   5.68 KiB          [emitted]
             dashboards/pcp-bpftrace-system-analysis.json   29.6 KiB          [emitted]
                  dashboards/pcp-redis-host-overview.json   48.2 KiB          [emitted]
            dashboards/pcp-vector-container-overview.json   10.4 KiB          [emitted]
                 dashboards/pcp-vector-host-overview.json   63.8 KiB          [emitted]
                           datasources/bpftrace/README.md  121 bytes          [emitted]
                datasources/bpftrace/css/query-editor.css   38 bytes          [emitted]
                        datasources/bpftrace/img/eBPF.png    155 KiB          [emitted]
    datasources/bpftrace/partials/annotations.editor.html  212 bytes          [emitted]
                datasources/bpftrace/partials/config.html   1.68 KiB          [emitted]
          datasources/bpftrace/partials/query.editor.html   1.75 KiB          [emitted]
                         datasources/bpftrace/plugin.json  569 bytes          [emitted]
                              datasources/redis/README.md  115 bytes          [emitted]
                          datasources/redis/img/redis.png   27.3 KiB          [emitted]
                          datasources/redis/img/redis.svg   5.22 KiB          [emitted]
       datasources/redis/partials/annotations.editor.html  212 bytes          [emitted]
                   datasources/redis/partials/config.html  115 bytes          [emitted]
             datasources/redis/partials/query.editor.html    1.4 KiB          [emitted]
                            datasources/redis/plugin.json  699 bytes          [emitted]
                             datasources/vector/README.md  117 bytes          [emitted]
                  datasources/vector/css/query-editor.css   63 bytes          [emitted]
                        datasources/vector/img/vector.png   42.8 KiB          [emitted]
                        datasources/vector/img/vector.svg   12.2 KiB          [emitted]
      datasources/vector/partials/annotations.editor.html  212 bytes          [emitted]
                  datasources/vector/partials/config.html   1.68 KiB          [emitted]
            datasources/vector/partials/query.editor.html   2.05 KiB          [emitted]
                           datasources/vector/plugin.json  580 bytes          [emitted]
                                         img/pcp-logo.svg      3 KiB          [emitted]
                     panels/flamegraph/css/flamegraph.css  560 bytes          [emitted]
                     panels/flamegraph/img/flamegraph.svg   21.1 KiB          [emitted]
                            panels/flamegraph/plugin.json  455 bytes          [emitted]
                                              plugin.json   2.36 KiB          [emitted]
    Entrypoint ./module = ./module.js
    Entrypoint ./datasources/redis/module = ./datasources/redis/module.js
    Entrypoint ./datasources/vector/module = ./datasources/vector/module.js
    Entrypoint ./datasources/bpftrace/module = ./datasources/bpftrace/module.js
    Entrypoint ./panels/flamegraph/module = ./panels/flamegraph/module.js
     [0] external "lodash" 42 bytes {0} {1} {2} {4} [built]
     [1] ./datasources/lib/models/datasource.ts 315 bytes {0} {1} {2} [built]
     [2] ./datasources/lib/utils.ts 1.99 KiB {0} {1} {2} [built]
     [3] external "react" 42 bytes {4} [built]
    [19] external "@grafana/data" 42 bytes {4} [built]
    [46] ./datasources/lib/services/panel_transformation_srv.ts 13 KiB {0} {1} {2} [built]
    [47] ./datasources/lib/services/value_transformation_srv.ts 2.6 KiB {0} {1} {2} [built]
    [48] ./datasources/lib/models/errors.ts 1.45 KiB {0} {1} {2} [built]
    [49] ./datasources/lib/pcp_query_ctrl.ts 3.44 KiB {0} {1} {2} [built]
    [51] external "@grafana/ui" 42 bytes {4} [built]
    [95] ./panels/flamegraph/module.tsx + 49 modules 40.2 KiB {4} [built]
         | ./panels/flamegraph/module.tsx 307 bytes [built]
         | ./panels/flamegraph/FlameGraphPanel.tsx 2.07 KiB [built]
         | ./panels/flamegraph/FlameGraphPanelEditor.tsx 2.94 KiB [built]
         | ./panels/flamegraph/types.ts 103 bytes [built]
         | ./panels/flamegraph/FlameGraphChart.tsx 4.83 KiB [built]
         | ./panels/flamegraph/model.ts 3.93 KiB [built]
         |     + 44 hidden modules
    [96] ./datasources/bpftrace/module.ts + 6 modules 36 KiB {0} [built]
         | ./datasources/bpftrace/module.ts 788 bytes [built]
         | ./datasources/bpftrace/datasource.ts 7.56 KiB [built]
         | ./datasources/bpftrace/query_ctrl.ts 2.36 KiB [built]
         | ./datasources/bpftrace/script.ts 469 bytes [built]
         | ./datasources/bpftrace/script_registry.ts 11.3 KiB [built]
         | ./datasources/bpftrace/completer.ts 9.21 KiB [built]
         | ./datasources/bpftrace/mode-bpftrace.ts 4.32 KiB [built]
    [97] ./datasources/redis/module.ts + 6 modules 54.3 KiB {1} [built]
         | ./datasources/redis/module.ts 740 bytes [built]
         | ./datasources/redis/datasource.ts 16 KiB [built]
         | ./datasources/redis/query_ctrl.ts 2.33 KiB [built]
         | ./datasources/redis/pmseries_srv.ts 23.6 KiB [built]
         | ./datasources/redis/completer.ts 9.51 KiB [built]
         | ./datasources/redis/mode-pmseries.ts 2.14 KiB [built]
         | ./datasources/redis/models/pmseries.ts 34 bytes [built]
    [98] ./datasources/vector/module.ts + 4 modules 22.9 KiB {2} [built]
         | ./datasources/vector/module.ts 756 bytes [built]
         | ./datasources/vector/datasource.ts 6.17 KiB [built]
         | ./datasources/vector/query_ctrl.ts 7.35 KiB [built]
         | ./datasources/vector/completer.ts 7.15 KiB [built]
         | ./datasources/vector/mode-pcp.ts 1.45 KiB [built]
    [99] ./module.ts + 1 modules 350 bytes {3} [built]
         | ./module.ts 105 bytes [built]
         |     + 1 hidden module
        + 94 hidden modules
Done in 14.85s.
$ cd ..
$ mv grafana-pcp performancecopilot-pcp-app
$ grafana-cli plugins install performancecopilot-pcp-app

Error: ✗ Failed to find requested plugin, check if the plugin_id is correct: 404 not found error

NAME:
   Grafana cli plugins install - install <plugin id> <plugin version (optional)>

USAGE:
   Grafana cli plugins install [arguments...]
$

I tried to copy grafana-pcp plugin to /var/lib/grafana/plugins, 
but I could not find grafana-pcp plugin from the web.

**Comment by jaehyuck-kwak** [comment]
FYI, I tried grafana 6.5.3-1.x86_64 and grafana-pcp v2.0.0-beta1 and it worked well.

**Comment by andreasgerstmayr** [comment]
`grafana-cli` is not required, did you restart `grafana-server` after moving the datasource to `/var/lib/grafana/plugins`?
Detailed instructions are at: https://grafana-pcp.readthedocs.io/en/latest/installation.html#from-source

> FYI, I tried grafana 6.5.3-1.x86_64 and grafana-pcp v2.0.0-beta1 and it worked well.

Great to hear! Closing this issue as it's resolved.
