### ISSUE TITLE
Unable to install BCC - Many panels in Grafana BPF trace system analysis dashboard are not working

### ISSUE THREAD

**Issue by chetanrjoshi777** [performancecopilot/grafana-pcp#35]
Installed the following on my linux server with these below versions:

root@sv-debian-02:/home/ranicete/bpftrace# cat /proc/version 
Linux version 4.9.0-8-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) ) #1 SMP Debian 4.9.130-2 (2018-10-27)

root@sv-debian-02:/home/ranicete/bpftrace# redis-server --version 
Redis server v=5.0.3 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=afa0decbb6de285f

root@sv-debian-02:/var/log/pcp/pmlogger/sv-debian-02# python --version
Python 2.7.16

root@sv-debian-02:/home/ranicete/bpftrace# grafana-server --v 
Version 6.6.1 (commit: 21bf8b71bc, branch: HEAD)

root@sv-debian-02:/home/ranicete/bpftrace# pcp --version 
pcp version 5.0.2

root@sv-debian-02:/home/ranicete/bpftrace# bpftrace --v 
bpftrace v0.9.4-17-g471e

Grafana pcp plugin - grafana-pcp-2.0.0-beta1

On Grafana web browser, under Vector dashboard, 2 panels are not working:
BCC Disk latency and Run queue latency. 
The error message is : 
Cannot find metric bcc.runq.latency. Please check if the PMDA is enabled. 

On Grafana web browser, under BPF trace system analysis and flamegraphs, lot of panels are not working:
The error message is : 
modprobe : FATAL : Module Kheaders not found in directory /lib/modules/4.9.0-8-amd64 definitions.h : 10.3: error unknown type name "pid_t"

Hence,tried to install BCC, but it failed with below error, can you please let me know how to proceed further?
root@sv-debian-02:/var/lib/pcp/pmdas/bcc# ./Install
[Wed Feb 19 20:25:48] pmdabcc(18427) Info: Initializing, currently in 'notready' state.
[Wed Feb 19 20:25:48] pmdabcc(18427) Info: Enabled modules:
[Wed Feb 19 20:25:48] pmdabcc(18427) Info: ['biolatency', 'sysfork', 'tcpperpid', 'runqlat']
[Wed Feb 19 20:25:48] pmdabcc(18427) Info: Configuring modules:
[Wed Feb 19 20:25:48] pmdabcc(18427) Info: biolatency
[Wed Feb 19 20:25:48] pmdabcc(18427) Info: sysfork
[Wed Feb 19 20:25:48] pmdabcc(18427) Info: tcpperpid
[Wed Feb 19 20:25:48] pmdabcc(18427) Info: runqlat
[Wed Feb 19 20:25:48] pmdabcc(18427) Info: Modules configured.
[Wed Feb 19 20:25:48] pmdabcc(18427) Info: Initializing modules:
[Wed Feb 19 20:25:48] pmdabcc(18427) Info: biolatency
[Wed Feb 19 20:25:48] pmdabcc(18427) Error: No module named 'bcc'
[Wed Feb 19 20:25:48] pmdabcc(18427) Error: Traceback (most recent call last):
  File "/var/lib/pcp/pmdas/bcc/pmdabcc.python", line 206, in init_modules
    mod = importlib.import_module('modules.%s' % self.modules[module][MODULE])
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/lib/pcp/pmdas/bcc/modules/biolatency.py", line 20, in <module>
    from bcc import BPF
ModuleNotFoundError: No module named 'bcc'

[Wed Feb 19 20:25:48] pmdabcc(18427) Error: Module biolatency not found, aborting.
[Wed Feb 19 20:25:48] pmdabcc(18431) Info: Initializing, currently in 'notready' state.
[Wed Feb 19 20:25:48] pmdabcc(18431) Info: Enabled modules:
[Wed Feb 19 20:25:48] pmdabcc(18431) Info: ['biolatency', 'sysfork', 'tcpperpid', 'runqlat']
[Wed Feb 19 20:25:48] pmdabcc(18431) Info: Configuring modules:
[Wed Feb 19 20:25:48] pmdabcc(18431) Info: biolatency
[Wed Feb 19 20:25:48] pmdabcc(18431) Info: sysfork
[Wed Feb 19 20:25:48] pmdabcc(18431) Info: tcpperpid
[Wed Feb 19 20:25:48] pmdabcc(18431) Info: runqlat
[Wed Feb 19 20:25:48] pmdabcc(18431) Info: Modules configured.
[Wed Feb 19 20:25:48] pmdabcc(18431) Info: Initializing modules:
[Wed Feb 19 20:25:48] pmdabcc(18431) Info: biolatency
[Wed Feb 19 20:25:48] pmdabcc(18431) Error: No module named 'bcc'
[Wed Feb 19 20:25:48] pmdabcc(18431) Error: Traceback (most recent call last):
  File "/var/lib/pcp/pmdas/bcc/pmdabcc.python", line 206, in init_modules
    mod = importlib.import_module('modules.%s' % self.modules[module][MODULE])
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/lib/pcp/pmdas/bcc/modules/biolatency.py", line 20, in <module>
    from bcc import BPF
ModuleNotFoundError: No module named 'bcc'

[Wed Feb 19 20:25:48] pmdabcc(18431) Error: Module biolatency not found, aborting.
Install: cannot determine the Performance Metrics Domain from domain.h.python

**Comment by chetanrjoshi777** [comment]
Updated the grafana-pcp plugin to v2.0.1. Now, 2 panels which were not working in Grafana Vector dashboard are removed as expected.
The issue is only on Grafana BPF trace system analysis dashboard. Many panels are still not working there. The error message on Grafana web browser is:
modprobe : FATAL : Module Kheaders not found in directory /lib/modules/4.9.0-8-amd64 definitions.h : 10.3: error unknown type name "pid_t"

**Comment by andreasgerstmayr** [comment]
> modprobe : FATAL : Module Kheaders not found in directory /lib/modules/4.9.0-8-amd64 definitions.h : 10.3: error unknown type name "pid_t"

You need to install the kernel headers (or use a more recent kernel version):
```
apt-get install linux-headers-$(uname -r)
```


Regarding BCC: For the BCC PMDA to work you'll need to have the bcc Python module installed, it's called `python-bpfcc` on Debian.

**Comment by andreasgerstmayr** [comment]
Closed due to inactivity.
