### ISSUE TITLE
Query remote systems from central Grafana?

### ISSUE THREAD

**Issue by tmonk42** [performancecopilot/grafana-pcp#40]
So I've been experimenting, and as best I can tell if I want to monitor remote systems, I either need to install PCP and Grafana on each system and then connect to grafana on each system as I want to view it's metrics, or I need to create a Vector datasource for each remote system I want to query.

I would really like to be able to build a dashboard on centralized grafana server(s) where I could select a hostname/ip from a list, and then view PCP metrics from that remote host. Is there a better way than having a datasource for each remote system? Something using pmproxy perhaps?

**Comment by natoscott** [comment]
@tmonk42 yes, using pmproxy you can have a centralised setup.  I recommend using a 'pmlogger farm' - see pmlogger_check(1) - to manage a set of pmlogger(1) process for multiple hosts.

The archives from these hosts are automatically discovered, can be cached in Redis and queried using the PCP+Redis datasource (metric labels are used to distinguish hosts).

**Comment by andreasgerstmayr** [comment]
fyi: in the next grafana-pcp release this functionality will also be available in the PCP Vector datasource (#52). You can override the default PCP host specification in each panel (i.e. every panel can connect to a different host *through* pmproxy), and with Grafana templating you can create a `$hostname` variable (with a dropdown) and then specify this template variable in each panel. Similar to the PCP Redis Host overview dashboard.
