### ISSUE TITLE
redis backfilling

### ISSUE THREAD

**Issue by andreasgerstmayr** [performancecopilot/grafana-pcp#43]
for the vector datasource, we can check if redis is configured and optionally backfill the history with data from redis

**Comment by natoscott** [comment]
> for the vector datasource, we can check if redis is configured and optionally backfill the history with data from redis

I think there may be no need to check... it should work to just make the REST request unconditionally & if it fails with a 404 then switch off the feature for subsequent requests?

**Comment by andreasgerstmayr** [comment]
implemented in #68
