### ISSUE TITLE
Dashboard of grafana-pcp does not show data.

### ISSUE THREAD

**Issue by sebasls** [performancecopilot/grafana-pcp#45]
Hi,
my settings:
RHEL 7.7
grafana-pcp 2.0.2
grafana-server 6.7.2
pcp 5.1.0-1
Redis server v=3.2.12
I am trying to collect statistics from different machines and be able to see from Grafana, but, the grafana-pcp dashboard does not show anything: it shows word 'services' continuously. In machine it is observed that pmlogger collects data, but, activity is not observed in pmproxy ports or in redis. The pmproxy and redis settings are the default.
Thanks

**Comment by andreasgerstmayr** [comment]
hi @sebasls, Redis version 5 is required. Please report if this solves the issue.

Cheers,
Andreas

**Comment by sebasls** [comment]
hi,
thanks for the quick reply, but follow the same problem.
# redis-server --version
Redis server v=5.0.8 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=22ef757b484107b2

**Comment by sebasls** [comment]
systemctl status pmproxy
● pmproxy.service - Proxy for Performance Metrics Collector Daemon
   Loaded: loaded (/usr/lib/systemd/system/pmproxy.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2020-04-03 16:08:40 CEST; 2 days ago
     Docs: man:pmproxy(8)
 Main PID: 2550 (pmproxy)
   CGroup: /system.slice/pmproxy.service
           └─2550 /usr/libexec/pcp/bin/pmproxy
Apr 03 16:08:40 ---- systemd[1]: Starting Proxy for Performance Metrics Collector Daemon...
Apr 03 16:08:40 ---- pmproxy[2300]: Starting pmproxy ...
Apr 03 16:08:40 ---- systemd[1]: Started Proxy for Performance Metrics Collector Daemon.


cat /var/log/pcp/pmproxy/pmproxy.log
Log for pmproxy on ---- started Fri Apr  3 16:08:40 2020
pmproxy: PID = 2550, PDU version = 2, user = pcp (993)
pmproxy request port(s):
  sts fd   port  family address
  === ==== ===== ====== =======
  ok    13       unix   /run/pcp/pmproxy.socket
  ok    14 44322 inet   INADDR_ANY
  ok    15 44323 inet   INADDR_ANY

Running 'pmseries disk.dev.read' returns nothing.

**Comment by andreasgerstmayr** [comment]
Hm, the versions look good now and the logs also don't show any error.
Did you restart pmproxy after installing redis version 5? Try to restart pmproxy.

> Running 'pmseries disk.dev.read' returns nothing.

That shows that there is no data in redis (yet).

> grafana-pcp dashboard does not show anything: it shows word 'services' continuously.

Can you make a screenshot of this or post the full message?

**Comment by sebasls** [comment]
I restarted pmproxy service after installing redis version 5.
![Capture](https://user-images.githubusercontent.com/63101514/78574504-5ea43200-782a-11ea-91ca-3d392744e7bf.PNG)

**Comment by andreasgerstmayr** [comment]
Hm, I've never seen that error before.

Can you run
```
curl http://localhost:44322/pmapi/context
```
and check if you get a JSON response?

And when opening Grafana in the browser, open the network analysis in the web developer console and check which request is stuck?

**Comment by sebasls** [comment]
curl http://localhost:44322/pmapi/context
^C
no response is obtained
... network analysis in the web browser:
![Capture](https://user-images.githubusercontent.com/63101514/78588994-cf097e00-783f-11ea-979b-520c991199fd.PNG)

**Comment by andreasgerstmayr** [comment]
@natoscott can you chime in here? pmproxy is running, but not responding to HTTP requests.
Usually this type of error is libuv related, but in this case it looks like pmproxy was compiled with libuv support. iirc Jason had a similar problem once, but I don't remember the conclusion and probably it got fixed months ago.

**Comment by natoscott** [comment]
Possibly firewall configuration blocking port 44322?  And maybe also blocking Redis on 6379?

The pmproxy.og also lacks a couple of lines I would have expected - e.g. from my local setup:

```
[Mon Apr  6 16:16:47] pmproxy(3711896) Info: OpenSSL 1.1.1d FIPS  10 Sep 2019 - no certificates found
[Mon Apr  6 16:16:47] pmproxy(3711896) Info: Redis slots, command keys, schema version setup
```

This means @sebasls your pmproxy is built without SSL support (that's OK), and no connection is established to Redis (if Redis 5 is indeed running locally, this indicates a problem - again, could be explained by ports being blocked).  Could also be something like selinux I guess ... any connection errors in system logs?

@sebasls is 'redis-cli PING' able to connect and communicate with Redis?

**Comment by sebasls** [comment]
All services are on the same machine; selinux disabled. In the log file there are only pmproxy service start and stop lines.
 redis-cli ping
PONG
When i start the pmproxy service, it shows that pmproxy connects to redis
redis-cli --stat
------- data ------ --------------------- load -------------------- - child -
keys       mem      clients blocked requests            connections
0          854.66K  2       0       31 (+0)             10

**Comment by natoscott** [comment]
> All services are on the same machine; selinux disabled.

OK.

> In the log file there are only pmproxy service start and stop lines.

This bit is wierd - if pmproxy successfully connects to Redis you will see this line in pmproxy.log:
[Tue Apr  7 16:31:51] pmproxy(3911215) Info: Redis slots, command keys, schema version setup

... but it is not in your log from before.

> When i start the pmproxy service, it shows that pmproxy connects to redis
> redis-cli --stat
> ------- data ------ --------------------- load -------------------- - child -
> keys mem clients blocked requests connections
> 0 854.66K 2 0 31 (+0) 10

I don't see how this can be, that we get a connection but no message logged to that effect in pmproxy.log - we're missing something there.  And it's possibly the same problem as your curl(1) command not returning - I've never seen that before either - it's like the connection is established but initial PDU exchanges stall.  Very odd.

Are you using a PCP you built locally on this RHEL 7.7 machine, with your own locally-installed libuv development headers and library?  Or the PCP packages from bintray?  I wonder if there's a mismatch between the compiled libraries and the installed libraries, or something like that.

**Comment by sebasls** [comment]
_Are you using a PCP you built locally on this RHEL 7.7 machine, with your own locally-installed libuv development headers and library?_
Yes
 rpm -qa |grep libuv
libuv-devel-1.34.0-1.el7.x86_64
libuv-1.34.0-1.el7.x86_64

**Comment by natoscott** [comment]
@sebasls that looks OK, so the mystery remains.  Only thing I can suggest is you try using the bintray.com/pcp/el7 PCP builds, and libuv from EPEL7 - I know other folk are having success with that combination.

**Comment by sebasls** [comment]
# yum list installed| grep libuv
libuv.x86_64                     1:1.34.0-1.el7     @epel
libuv-devel.x86_64               1:1.34.0-1.el7     @epel
libuv-static.x86_64              1:1.34.0-1.el7     @epel
and bintray.com/pcp/el7 PCP builds
but, everything remains the same:
# curl http://localhost:44322/pmapi/context
<HTML>
<HEAD><TITLE>Redirection</TITLE></HEAD>
<BODY><H1>Redirect</H1></BODY>
Running 'pmseries disk.dev.read' returns nothing

**Comment by andreasgerstmayr** [comment]
I just tried to reproduce this with a fresh RHEL 7.7 VM on Azure:
```
sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
sudo vim /etc/yum.repos.d/bintray.repo
sudo yum install -y pcp rh-redis5
sudo systemctl start pmcd pmlogger pmproxy rh-redis5-redis
```

bintray.repo:
```
#bintraybintray-pcp-el7 - packages by pcp from Bintray
[bintraybintray-pcp-el7]
name=bintray-pcp-el7
baseurl=https://dl.bintray.com/pcp/el7
gpgcheck=0
repo_gpgcheck=0
enabled=1
```

Everything works as expected:
```
[pcp@rhel7 ~]$ curl http://localhost:44322/pmapi/context
{"context":1326004372,"source":"3a72af3c41aa74512bebb55d76ffbf6c0e97190e","hostspec":"rhel7","labels":{"domainname":"localdomain","hostname":"rhel7","machineid":"b2211d793fb547419243109dc1f3c0af"}}

< then wait a few minutes... >

[pcp@rhel7 ~]$ pmseries disk.dev.read
5693f9152b7e74e10c56a4252e25ae45eb9e3d9b
```

afaics pmproxy never sends a redirect, so...idk what's going on there. Maybe try a `sudo ss -lntp` to check if actually pmproxy is listening or something else..
If you've compiled PCP from source at first, and then installed the bintray packages, you may have still the self-compiled version in /usr/local/bin/pcp and the bintray version in /usr/bin/pcp. Does `systemctl cat pmproxy` contain this line: `ExecStart=/usr/share/pcp/lib/pmproxy start`?

**Comment by sebasls** [comment]
congratulations...

some library that was not removed during the pcp version change.... cleaned, reinstalled pcp and working
thanks for your time

**Comment by andreasgerstmayr** [comment]
Ok, great that we could resolve this issue now :)
