### ISSUE TITLE
hotproc does not work as I expected and does not show up on grafana dashboard

### ISSUE THREAD

**Issue by rduttainfinera** [performancecopilot/grafana-pcp#46]
I have added and loaded one hotproc predicate as:

root@chassis1-gx:/var/lib/pcp/pmdas/proc# pmstore hotproc.control.config cpuburn > 0.5
root@chassis1-gx:/var/lib/pcp/pmdas/proc# pmstore hotproc.control.reload_config "1"
hotproc.control.reload_config old value=0 new value=1

dumped the data pertaining to the metric, instead of one qualified process it shows a bunch:
root@chassis1-gx:/var/lib/pcp/pmdas/proc# pminfo -ft hotproc.predicate.cpuburn

hotproc.predicate.cpuburn [CPU utilization per "interesting" process]
    inst [1 or "000001 /usr/bin/qemu-aarch64"] value 0
    inst [25641 or "025641 /usr/bin/qemu-aarch64"] value 0.54307693
    inst [25736 or "025736 /usr/bin/qemu-aarch64"] value 0
    inst [20990 or "020990 /usr/bin/qemu-aarch64"] value 0.00076923077
    inst [940 or "000940 /usr/bin/qemu-aarch64"] value 0
    inst [946 or "000946 /var/lib/pcp/pmdas/proc/pmdaproc"] value 0
    inst [949 or "000949 /usr/bin/qemu-aarch64"] value 0
    inst [952 or "000952 /usr/bin/qemu-aarch64"] value 0
    inst [955 or "000955 /usr/bin/qemu-aarch64"] value 0

Here is a top 
---------------
root@chassis1-gx:/var/lib/pcp/pmdas/proc# top
top - 18:18:12 up 15:26,  0 users,  load average: 1.00, 1.02, 1.00
Tasks:  13 total,   0 running,  13 sleeping,   0 stopped,   0 zombie
%Cpu(s): 18.2 us,  9.1 sy,  0.0 ni, 51.5 id, 15.2 wa,  0.0 hi,  6.1 si,  0.0 st
MiB Mem :   1966.3 total,    120.5 free,    543.3 used,   1302.5 buff/cache
MiB Swap:   1024.0 total,   1013.4 free,     10.6 used.   1265.0 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
25641 root      20   0  125752  12276   3632 D  56.2   0.6 163:28.19 bash
    1 root      20   0  125236  10744   4932 S   0.0   0.5   0:00.09 start.sh
  935 pcp       20   0  130492  14800   5328 S   0.0   0.7   0:05.23 pmcd
  940 root      20   0  128840  11380   5468 S   0.0   0.6   0:00.49 pmdaroot
  946 root      20   0  129336  15040   5820 S   0.0   0.7   0:29.87 pmdaproc
  949 root      20   0  128228   8736   5120 S   0.0   0.4   0:00.94 pmdaxfs
  952 root      20   0  128784  12220   5516 S   0.0   0.6   0:23.02 pmdalinux
  955 root      20   0  128204  10844   5060 S   0.0   0.5   0:00.40 pmdakvm
 3119 pcp       20   0  129004  14428   5972 S   0.0   0.7   0:00.93 pmie
20867 pcp       20   0  130012  15132   5712 S   0.0   0.8   0:03.23 pmlogger
20990 root      20   0  125624  13792   5224 S   0.0   0.7   0:00.94 bash
25736 root      20   0  123292   5592   3576 S   0.0   0.3   0:00.01 sleep
25748 root       0   0  127068  10960   4996 0   0.0   0.5   0:00.00 /usr/bin/top

**First, should not hotproc show only processes that qualifies the predicate ?** 

**Secondly, when I used vector datasource on grafana, if I use a dash board collecting hotproc.predicate.cpuburn, nothing shows up.** 
I changed it to hotproc.total.cpuburn then it show the total, which means the dashboard is capable of fetching the data. May be hotproc.predicate.cpuburn does not produce valid data for the vector query. 

Please help providing me some successful steps of creating hotproc predicates and visualizing them on grafana.

Regards,
Raj

**Comment by rduttainfinera** [comment]
One more question in the same context:
--------------------------------------------
We added a new few metrics and they are available on Vector - showing up on grafana and I can dump them from pmlogger (pmlc), but these new metric do not show up on pmseries or redis. Is there something else needed to be done differently to make them qualify for pmseries query or redis storage. This new metric is collected in regular interval and it does not return any null data.
Regards,
Raj

**Comment by andreasgerstmayr** [comment]
> **Secondly, when I used vector datasource on grafana, if I use a dash board collecting hotproc.predicate.cpuburn, nothing shows up.**
> I changed it to hotproc.total.cpuburn then it show the total, which means the dashboard is capable of fetching the data. May be hotproc.predicate.cpuburn does not produce valid data for the vector query.

pminfo is showing the metrics, but Grafana using the Vector datasource is not? Does it show up if you refresh the browser (there was a bug with autocompletion caching)?

> We added a new few metrics and they are available on Vector - showing up on grafana and I can dump them from pmlogger (pmlc), but these new metric do not show up on pmseries or redis. Is there something else needed to be done differently to make them qualify for pmseries query or redis storage.

Are these metrics stored in archives by pmlogger? All metrics logged by pmlogger should be stored into redis. I've added an architecture overview diagram recently to the documentation: https://grafana-pcp.readthedocs.io/en/latest/architecture.html

Which versions of PCP, Grafana, grafana-pcp, redis are you using?

**Comment by andreasgerstmayr** [comment]
The reason these hotproc metrics are not shown in Grafana is because they require authentication. pminfo uses unix domain sockets for that, but by default Grafana doesn't use authentication. You can set up authentication in Grafana by following this guide: https://grafana-pcp.readthedocs.io/en/latest/datasources/authentication.html
