### ISSUE TITLE
Stored data disappear

### ISSUE THREAD

**Issue by sebasls** [performancecopilot/grafana-pcp#49]
**Describe the bug**
The data collected since a date is not displayed. We have been collecting data for more than a week and everything was shown from the dashboard, but suddenly, there is data that is not shown. Depending on the type of metric, it shows more to less data.

**To Reproduce**

**Expected behavior**
Show all data from the date it started to be collected.
On the other hand, I have to say that I also don't know how to retain data for a specific amount of time.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/63101514/81793279-734ea680-9509-11ea-8cdc-6849f59024c9.PNG)

**Versions (please complete the following information):**
 - Performance Co-Pilot: 5.0.3
 - Grafana: 6.7.2
 - grafana-pcp: 2.0.2
- Redis (if applicable): 5.0.8

**Additional context**

**Comment by andreasgerstmayr** [comment]
Can you post the contents of `/var/log/pcp/pmproxy/pmproxy.log`?

**Comment by sebasls** [comment]
attached file
[pmproxy.log](https://github.com/performancecopilot/grafana-pcp/files/4651082/pmproxy.log)
thanks

**Comment by sebasls** [comment]
Hi,
excuse my clumsiness, but I still don't understand how to have the same old data from all the machines. With the default settings, the age of the displayed data is different for each machine. I would like to know what to modify to have 1 month of data for each machine.
Thanks

**Comment by natoscott** [comment]
The stream.expire and stream.maxlen settings in the [pmseries] section of pmproxy.conf affect the behaviour you're seeing, particularly the maxlen setting in your case I think.

These values provide a balance between memory used (by Redis) and the logged values we're able to access from it.

**Comment by sebasls** [comment]
First of all, thanks for your time.
I understand the parameter to modify, but, of all the machines that I am collecting data, only the local one retains data for one day, the rest: remote machines, keeps data all the time.
