### ISSUE TITLE
Filter requests by labels

### ISSUE THREAD

**Issue by Fodoj** [performancecopilot/grafana-pcp#50]
I could not find the information in docs, so I assume the feature is not there. I am trying to get metric for particular instance, but after trying many different ways to write a query, I came a conclustion that this is not yet supported. Is that so?

What I mean in particular is the possibility to write queries like:

```
cgroup.cpu.stat.usage{instance="xxxxxxx"}
```

**Comment by natoscott** [comment]
@Fodoj see the 'METADATA QUALIFIERS AND OPERATORS' section of the pmseries(1) man page - you want:

```
cgroup.cpu.stat.usage{instance.name="xxxxxxx"}
```

**Comment by Fodoj** [comment]
I tried that, among many other ways to specify metadata qualifiers (inst, instance, instance.name etc), each of the resulted in Grafana telling me that metric name is invalid.

For example:

![image](https://user-images.githubusercontent.com/78866/82196576-28160880-98fa-11ea-941a-e82a6d981943.png)

Then when I try to filter for user.slice like this:

* cgroup.cpu.stat.usage{instance.name="/user.slice"}
* cgroup.cpu.stat.usage{instance="/user.slice"}
* cgroup.cpu.stat.usage{inst="/user.slice"}
* cgroup.cpu.stat.usage{instname="/user.slice"}

I always get this:

![image](https://user-images.githubusercontent.com/78866/82196882-8e029000-98fa-11ea-8bce-ae6045fca1c5.png)


```
Cannot find metric QUERY. Please check if the PMDA is enabled.
```

Where QUERY is one of the above mentioned ones.

If I query pmproxy directly, I get:

```
curl http://localhost:44322/metrics\?names=cgroup.cpu.stat.usage | grep user.slice
cgroup_cpu_stat_usage{instname="/user.slice",instid="1",cgroup="/user.slice",hostname="localhost.localdomain",machineid="3d04244d95ee47eba05e7d3e456d1900",domainname="localdomain"} 192630582455
# here comes many other metrics with other labels
```

**Comment by andreasgerstmayr** [comment]
Sorry, I think there was some confusion over the data sources.
From the screenshot I can see you're using PCP Vector, and with this datasource it' currently not supported to filter based on the instance name. Support for derived metrics is planned (#13), which allows filtering based on instances. The `cgroup.cpu.stat.usage{instance.name="xxxxxxx"}` syntax works only for PCP Redis.

For now, you can add a **series override** in Grafana:
![2020-05-19-150858_1163x221_scrot](https://user-images.githubusercontent.com/538011/82330250-e01ee080-99e2-11ea-993d-ff6d15934008.png)

Which effectively hides the sda instance from the graph in this example. It supports regex, so you write a regex which applies to all instances which you want to hide.

**Comment by Fodoj** [comment]
Understood, thanks for clarification!
