### ISSUE TITLE
Data Sources not appearing

### ISSUE THREAD

**Issue by JoshKeegan** [performancecopilot/grafana-pcp#67]
**Data source:** All

**Describe the bug**
After installing the grafana-pcp plugin, no new PCP data sources are available.

**To Reproduce**
 - `docker create --name grafana-pcp-repro -e GF_INSTALL_PLUGINS="https://github.com/performancecopilot/grafana-pcp/archive/v2.0.2.zip;grafana-pcp" -p 3000:3000 grafana/grafana:7.1.5`
 - `docker container start grafana-pcp-repro`
 - Wait a minute for grafana to start up
 - `docker logs grafana-pcp-repro` & check last line of output is "HTTP Server Listen", so grafana has started
 - We now restart grafana after installing plugins:
 - `docker container stop grafana-pcp-repro`
 - `docker container start grafana-pcp-repro`
 - Connect to grafana via web browser (http://localhost:3000 if running docker locally)
 - Login as admin/admin
 - Go to configuration/data sources & click add data source
 - No PCP options listed

You can cleanup by deleting the docker container with `docker container rm -f grafana-pcp-repro`

**Expected behavior**
The PCP data sources are available

**Screenshots**

**Versions (please complete the following information):**
 - Performance Co-Pilot: N/A
 - Grafana: 7.1.5 (also tested with 6.7.2)
 - grafana-pcp: 2.0.2
- Redis (if applicable): N/A

**Additional context**
N/A

**Comment by andreasgerstmayr** [comment]
Thanks for the detailed steps to reproduce!
Looks like you're missing a step to enable the plugin. Go to Configuration -> Plugins -> Performance Co-Pilot and click on the Enable button. Then the datasources will appear.

Let me know if it works for you.

**Comment by JoshKeegan** [comment]
Yes, that was it! Thankyou
