### ISSUE TITLE
Not able to specify hostspec in grafana

### ISSUE THREAD

**Issue by praveen-pcp** [performancecopilot/grafana-pcp#72]
I am using PCP in distributed manner.
There are 4 hosts-

Host1, Host2 : runs only pmcd
Host3: runs only pmproxy
Host4: running only Grafana server with pcp vector plugin.
I am using Grafana pcp-vector to connect to Host1 & Host2 pmcd via pmproxy running on Host3.

But I am not able to specify pmcd hostspec in grafana url.
Please suggest a procedure to define hostspec.

**Comment by andreasgerstmayr** [comment]
This new feature is already merged in master (see #52), and will be part of the upcoming grafana-pcp version 3.0 (see https://github.com/performancecopilot/grafana-pcp/blob/master/CHANGELOG.md).

Note that grafana-pcp version 3.0 is not released yet, but you can try it from the latest sources: https://grafana-pcp.readthedocs.io/en/latest/installation.html#from-source
