### ISSUE TITLE
Network Error: NetworkError when attempting to fetch resource.. To use this data source, please configure the URL in the query editor.

### ISSUE THREAD

**Issue by Wils3B** [performancecopilot/grafana-pcp#79]
Environment description:

- Client OS: Debian 10
- Monitored OS: Debian 10
- PCP Version: 4.3.1
- Grafana Version: 7.4.3
- Grafana-PCP Version: 3.0.3

Issue description:
When I test my pcp-vector configuration it always shows me `Network Error: NetworkError when attempting to fetch resource.. To use this data source, please configure the URL in the query editor.`, but yet when I use the same ip address with Netflix Vector, I get all the metrics and graphs.
I even tried to use the browser as an access method and the test request returns an `HTTP 400 error`.
Please could someone help me to solve this problem?

**Comment by andreasgerstmayr** [comment]
grafana-pcp only supports PCP version 5 or higher. Can you try it with PCP from debian testing (https://packages.debian.org/bullseye/pcp)?

**Comment by Wils3B** [comment]
Thank you @andreasgerstmayr for your answer but i cannot set up my web server with a testing version of debian, please is there a linux distribution with a stable version that supports pcp 5 ?

**Comment by andreasgerstmayr** [comment]
RHEL 8.2+, CentOS, Ubuntu 20.04+ for example.
You can also install the packages from https://bintray.com/pcp with your current Debian stable installation. But Bintray will shut down in May unfortunately, we're currently in the progress of looking for an alternative service to host our latest PCP distribution packages.

**Comment by Wils3B** [comment]
Thank you @andreasgerstmayr it work for my server

**Comment by nvjacobo** [comment]
Hi, 

I have same issue 

My setup 
- Client OS: Debian 10
- Monitored OS: Fedora 33 x64 
- PCP Version: 5.3.1-1
- Grafana Version: 7.4.3
- Grafana-PCP Version: 3.0.2

Thanks


-
