### ISSUE TITLE
backendSrv.fetch is not a function error.

### ISSUE THREAD

**Issue by whitingjr** [performancecopilot/grafana-pcp#81]
**Data source:**
PCP Vector

**Describe the bug**
Editing the PCP Vector datasource and selecting Save & Test shows this error

`Network Error: this.backendSrv.fetch is not a function. To use this data source, please configure the URL in the query editor.`

**To Reproduce**
1. Go to Configuration > Datasources > PCP Vector
2. Click on Save & Test button

**Expected behavior**
 The test to complete without error. The Dashboard to display metrics.

**Screenshots**
![Screenshot from 2021-04-23 14-18-59](https://user-images.githubusercontent.com/708428/115894871-ac99d100-a451-11eb-88b8-05d69365459a.png)

**Versions (please complete the following information):**
 - Performance Co-Pilot:2.0.2
 - Grafana:7.0.6
 - grafana-pcp:3.0.3

**Additional context**

Using curl to make a request on the web service for pmproxy shows it can be connected too

```
# curl -v http://127.0.0.1:44322/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 44322 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:44322
> User-Agent: curl/7.61.1
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< Connection: Keep-Alive
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: Accept, Accept-Language, Content-Language, Content-Type
< Content-Length: 204
< Content-Type: text/html
< Date: Fri, 23 Apr 2021 13:32:30 GMT
< 
<html>
<head><title>400 Bad Request</title></head>
<body>
<h1>400 Bad Request</h1>
<p><b>unknown servlet</b>: no handler for URL</p><hr>
<p><small><i>pmproxy/5.1.1</i></small></p>
</body>
</html>
* Connection #0 to host 127.0.0.1 left intact
#
```
grafana-pcp shows this in the logs
```

t=2021-04-23T13:31:07+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2021-04-23T13:31:09+0000 lvl=dbug msg="Received command to update data source" logger=datasources url=http://127.0.0.1:44322
t=2021-04-23T13:31:09+0000 lvl=dbug msg="Applying default URL parsing for this data source type" logger=datasource type=pcp-vector-datasource url=http://127.0.0.1:44322
t=2021-04-23T13:31:17+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
```
indicating the configuration was saved with an identical url.

**Comment by andreasgerstmayr** [comment]
Please try with a recent version of Grafana (`>= 7.3.3`), version `7.0.6` is too old.

**Comment by whitingjr** [comment]
@andreasgerstmayr ok i'll try doing that and give feedback.

**Comment by whitingjr** [comment]
Using the current latest container version Grafana 7.5.4 solves this issue.
