### ISSUE TITLE
#NetworkError when attempting to fetch resource with linksmart sensor things datasource

### ISSUE THREAD

**Issue by awskhd** [performancecopilot/grafana-pcp#86]
![issue](https://user-images.githubusercontent.com/62724160/119055024-de5a7500-b9c8-11eb-990b-5cb3c9f0a1f3.PNG)

**Comment by andreasgerstmayr** [comment]
Can you give a little bit more information?

This project only provides the PCP Redis, PCP Vector and PCP bpftrace datasources, there is no linksmart sensor things datasource. grafana-pcp is a plugin for Grafana to read data from [Performance Co-Pilot](https://pcp.io).
