### ISSUE TITLE
Skipping loading plugin due to problem with signature with latest grafana-pcp version 3.2.1

### ISSUE THREAD

**Issue by ChristophKieser** [performancecopilot/grafana-pcp#94]
**Data source:** All

**Describe the bug**
After downloading and installing the grafana-pcp plugin no new PCP Plugins are available under Configuration -> Plugins -/> Performance Co-Pilot. This only happens with the current version 3.2.1, earlier versions (<= 3.2.0) seem unaffected.

**To Reproduce**

- Create docker-compose file (attached)
- Run _docker-compose up -d grafana_
- Wait a minute
- Run _docker-compose logs -f grafana_
- In the logs we can see the error that the loading of the plugins is skipped due to "problem with signature"
- You can cleanup with: docker-compose stop grafana && docker-compose rm -f grafana

**Expected behavior**
The grafana-pcp plugins are downloaded and activated and ready to be used. 

**Versions (please complete the following information):**
 - Performance Co-Pilot: 5.2.6
 - Grafana: v8.3.3 (30bb7a93ca)
 - grafana-pcp: v3.2.1
- Redis (if applicable): -/-

**docker-compose**
[docker-compose.txt](https://github.com/performancecopilot/grafana-pcp/files/7756144/docker-compose.txt)

**Logs**
[logs.txt](https://github.com/performancecopilot/grafana-pcp/files/7756158/logs.txt)

**Comment by andreasgerstmayr** [comment]
Hi Christoph,

the plugin is currently under review by the Grafana team. Once it is reviewed, we'll get a new key to digitally sign it and it will be published in the Grafana plugin catalog at https://grafana.com/grafana/plugins/

In the meantime you can enable this plugin by specifying the following environment variable in your docker compose file:
```
GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS="performancecopilot-pcp-app,pcp-redis-datasource,pcp-vector-datasource,pcp-bpftrace-datasource,pcp-flamegraph-panel,pcp-breadcrumbs-panel,pcp-troubleshooting-panel"
```

**Comment by benpbolton** [comment]
On a local grafana installation (Ubuntu 20), you might need to modify `/etc/grafana/grafana.ini` to include a 

```
allow_loading_unsigned_plugins = performancecopilot-pcp-app
```

... and after a restart, hitting (eg. at localhost:3000 http://localhost:3000/plugins/performancecopilot-pcp-app ) should present you with the ability to enable the plugin.

**Comment by andreasgerstmayr** [comment]
grafana-pcp is now available in the Grafana Plugin Marketplace: https://grafana.com/grafana/plugins/performancecopilot-pcp-app/ and all versions since v4 have a valid signature.
