### ISSUE TITLE
Random error messages: "Request Completed" status=502 in Grafana 7.5.12 after upgrading from 7.1.5

### ISSUE THREAD

**Issue by johanmha** [performancecopilot/grafana-pcp#98]
**Data source:**
Prometheus and probably others

**Describe the bug**
After upgrading to Grafana version 7.5.12 from 7.1.5, gets a lot of log messages with 

`t=2022-02-10T18:50:07+0000 lvl=eror msg="Request Completed" logger=context userId=23 orgId=1 uname=xx@xx.com method=GET path=/api/datasources/proxy/29/api/v1/query_range status=502 remote_addr=xx.xx.xx.xx time_ms=60 size=0 referer=https://xxx.com`

at random times when doing queries.  

**Versions (please complete the following information):**
 - Grafana: 7.5.12

**Additional context**
This issue could be related, but seems to be only when upgrading to 6.4, and we have upgraded from 7.1.5 to 7.5.12: https://github.com/grafana/grafana/issues/20096
This could also be related but seems to be only for Live feature in Grafana 8. Could it be an issue even in 7.5.12?

Often the error "Data proxy error" is logged in relation to "Request Completed" error

**Comment by andreasgerstmayr** [comment]
Hi @johanmha,

> Data source: Prometheus and probably others

This repository is about grafana-pcp, a plugin for Grafana. It does not contain code of Grafana itself or the prometheus data source. I think you want to raise this issue at https://github.com/grafana/grafana.
